// All colors live here so a new theme is just another object with the same keys.
export const classicTheme = {
  name: 'classic',
  background: '#10103a',
  wall: '#6ea8ff',
  slingshot: '#ff6ec7',
  bumper: '#ff9800',
  bumperLit: '#fff176',
  bumperRim: '#ffffff',
  flipper: '#4caf50',
  ball: '#e8e8e8',
  plunger: '#bbbbbb',
  text: '#ffffff',
  textMuted: '#9aa0c8',
  danger: '#ff5252',
  warning: '#ffb74d',
  overlay: 'rgba(0,0,0,0.7)',
  wormhole: '#b388ff',
  wormholeCore: '#1a0b3d',
  ramp: '#26c6da',
  rollover: '#4fc3f7',
  rolloverLit: '#fff176',
  dropTarget: '#ef5350',
  dropTargetDown: '#3a2a3a',
  lock: '#ffa726',
  banner: '#fff176',
};
